packages:
  - packages/*

allowBuilds:
  '@serialport/bindings': true
  bufferutil: true
  esbuild: true
  libxmljs: true
  serialport: true
  sharp: true

onlyBuiltDependencies:
  - '@serialport/bindings'
  - bufferutil
  - esbuild
  - libxmljs
  - serialport
  - sharp
