import { bass } from "./sound/bass";
import { click } from "./sound/click";
import { feedback } from "./sound/feedback";
import { gainChange } from "./params/gainChange";
import { metronome } from "./sound/metronome";
import { simulate } from "./sound/simulate";
import { sinewave } from "./sound/sinewave";
import { whitenoise } from "./sound/whitenoise";
import { initAudio } from "./init/initAudio";
import { accelarateOsc } from "./sound/accelarateOsc";
import { gpsOsc } from "./sound/gpsOsc";
export { bass, click, feedback, gainChange, metronome, simulate, sinewave, whitenoise, initAudio, accelarateOsc, gpsOsc, };
