export const flagState = {
    start: false,
    recLatency: true,
    recordFlag: false,
    timelapseFlag: false,
    otherStreamFlag: "",
    chatFlag: false,
    simulate: false,
    timelapse: false,
    emoji: false,
    socketId: "",
    gpsFlag: false,
    accelarateFlag: false,
    gpsOscFlag: false,
    accelarateOscFlag: false,
};
